export const PRODUCT_LIST_REQ = "PRODUCT_LIST_REQ";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_CLEAR = "PRODUCT_LIST_CLEAR";

export const PRODUCT_INFO_REQ = "PRODUCT_INFO_REQ";
export const PRODUCT_INFO_SUCCESS = "PRODUCT_INFO_SUCCESS";
export const PRODUCT_INFO_FAIL = "PRODUCT_INFO_FAIL";

export const PRODUCT_BUY_REQ = "PRODUCT_BUY_REQ";
export const PRODUCT_BUY_SUCCESS = "PRODUCT_BUY_SUCCESS";
export const PRODUCT_BUY_FAIL = "PRODUCT_BUY_FAIL";
export const PRODUCT_BUY_CLEAR = "PRODUCT_BUY_CLEAR";